### ISSUE TITLE
NativeCallProxy.h seems to be removed from the Libraries folder in the Unity-iPhone xcode project

### ISSUE THREAD

**Issue by SpencerIO** [Unity-Technologies/uaal-example#12]
NativeCallProxy.h seems to be removed from the Libraries folder in the Unity-iPhone xcode project. I'm not sure if there is a replacement. It works to comment out the header and remove NativeCallsProtocol from the AppDelegate Interface.

<img width="246" alt="Screen Shot 2020-01-31 at 8 53 39 PM" src="https://user-images.githubusercontent.com/5199953/73587106-f45ac400-446b-11ea-862a-dfd04851a9e5.png">

**Comment by emandravickas** [comment]
Hi there! NativeCallProxy.h/NativeCallProxy.mm contains code that acts as a bridge between your Unity application scripts and host iOS application.  In the current example these files will be copied from Assets/Plugins/iOS to exported project as native plugins. Export process would skip this if these files would not be marked as iOS platform native plugins. Could you check if this is not the case? Files should be marked as follows:
![Screen Shot 2020-02-03 at 12 18 56](https://user-images.githubusercontent.com/39412189/73645132-60614600-467f-11ea-9660-66e0d7889f11.png)
 
After successful export Libraries folder should look like this:
<img width="276" alt="Screen Shot 2020-02-03 at 11 54 36" src="https://user-images.githubusercontent.com/39412189/73644189-8a196d80-467d-11ea-8cfd-fcc97a4b461b.png">

**Comment by SpencerIO** [comment]
@emandravickas You are correct good sir. Pardon my overlooking the fact that NativeCallProxy.h is a file in the uaal-example Unity project. I was working off my own Unity project. NativeCallProxy is very useful.

Props to all working on Uaal!

**Comment by dannyhertz** [comment]
@SpencerIO hey! I am also running into issues with NativeCallProxy. I make sure to mark the header as public and add it to the framework target but whenever I try to actually use it I run into 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FrameworkLibAPI", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
```

Seems like the only example I was able to see work properly use some runtime trickery like this

```[NSClassFromString(@"FrameworkLibAPI") registerAPIforNativeCalls:self];```

What method are you using to use it? Thanks!

**Comment by KlutchKyle** [comment]
> Also, make sure that the Target Membership is set to "Public" on `NativeCallProxy.h`. @emandravickas , shouldn't this be the default setting when Unity builds the player?
> <img alt="Screenshot 2022-04-21 at 17 02 53" width="378" src="https://user-images.githubusercontent.com/2692844/164488036-55ba70f3-487a-413d-bebc-4bfdf6e3d54f.png">

Also, accidentally built without changing this setting and it wouldn't build without doing: Product > Clean Build Folder. Thank you!
