### ISSUE TITLE
ERROR: Could not find method implementation() for arguments [project ':unityLibrary'] on project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by brucelane** [Unity-Technologies/uaal-example#13]
hi,
The gradle sync fails with this error:
ERROR: Could not find method implementation() for arguments [project ':unityLibrary'] on project ':app' of type org.gradle.api.Project.
Any hint?

**Comment by brucelane** [comment]
oh, it should be in the dependencies section like this?
```apply plugin: 'com.android.application'
dependencies {
    implementation project(':unityLibrary')
    implementation fileTree(dir: project(':unityLibrary').getProjectDir().toString() + ('\\libs'), include: ['*.jar'])```
No more error, but Show Unity makes the app quit now...
I'm using Unity 2019.3.0.f6

**Comment by emandravickas** [comment]
Hi Bruce! Perhaps you could post Logcat output?

**Comment by brucelane** [comment]
It works now.
Good to know : don't update Gradle

**Comment by horatiu665** [comment]
@brucelane what version should Gradle be for this to work? I never got your original error, but "Show Unity' also quits the app for me.

my attempt now is to update everything to the latest version.

Hint: installing NDK latest version, then attempting build, leads to having to install NDK version 20.0.5594570 again. obv shouldn't update Everything...

**Comment by brucelane** [comment]
I used gradle 3.2.0

**Comment by horatiu665** [comment]
Thanks. Now I got it to work finally. 

My error was actually a missing libmain.so which was solved by changing Scripting Backend to IL2CPP instead of Mono, and enabling ARMv8 target architecture, because I was testing on a Pixel 2.

Versions used (actually I don't know exactly what I'm doing but here it is):
Android Gradle Plugin Version 3.6.1
Gradle Version 5.6.4
Unity version 2019.3.4f1

**Comment by emandravickas** [comment]
Hi guys! Just to build on @horatiu665 comment. If exported android project supports only ARMv7  for example, its gradle script will contain `ndk { abiFilters 'armeabi-v7a' }`  filter which will make sure that  app will be ran using this architecture in both 32 and 64 bit systems. Problems starts when we use host project to ran unity app. In UaaL case host app project contains it's own gradle scripts and if there is no filter or it includes ARMv8 as well, app will use this architecture on devices that supports it. In this case host app will launch, but will crash later while attempting to start unity app as it will not contain required architecture binaries.

**Comment by KainanSu** [comment]
If an error occurs in a higher version
Unity: Failed to load 'libmain.so', the application will terminate.

Try the following method
https://github.com/f111fei/react-native-unity-view/issues/142#issuecomment-557162700
