### ISSUE TITLE
I could not find: com.company.product

### ISSUE THREAD

**Issue by Explorerli** [Unity-Technologies/uaal-example#14]
Hi,

When I follow this tutorial: '[Integration Unity as a library in native Android app Version 2](https://forum.unity.com/threads/integration-unity-as-a-library-in-native-android-app-version-2.751712/)'.

I got an error, I could not find '**com.company.product**' in '**MainUnityActivity.java**'.

MainUnityActivity.java: 
![image](https://user-images.githubusercontent.com/44357820/74582153-00f62500-4ff3-11ea-9d40-c63576a2587b.png)

I don't have '**com.company.product**'.

I could not extend '**OverrideUnityActivity**'.

But I found OverrideUnityActivity.java in 'UnityProject\Assets\Plugins\Android\'.

How do I solve this problem?

Thank you in advance.

**Comment by emandravickas** [comment]
Hey! Sorry to hear that you are having this issue. OverrideUnityActivity.java is in fact placed in UnityProject\Assets\Plugins\Android folder. It is considered to be an android plugin, and should be copied during project export procedure. If you do not have it inside your exported unityLibrary project (it should be inside unityLibrary\src\main\java\com\company\product\ folder) it is most likely that it is not marked as Android plugin. Could you check that? To do so you need to open Unity Editor, find and click on OverrideUnityActivity.java in assets and check "Android" checkbox in file inspector window.

**Comment by emandravickas** [comment]
I'm assuming the issue was resolved. Feel free to reopen if it is not.
