### ISSUE TITLE
How to use Unity as a Library integration example to iOS with Swift

### ISSUE THREAD

**Issue by daminhtung** [Unity-Technologies/uaal-example#17]
I want to integrate Unity into my iOS project using **swift** not **Objective-c**.
Is there any way to integrate Unity that use Swift?

Best regards !

**Comment by daminhtung** [comment]
I did it, I will share later

**Comment by Fedd9** [comment]
Hi @daminhtung could you share your solution please?

**Comment by superbderrick** [comment]
hey buddy , @daminhtung any update?
