### ISSUE TITLE
'UnityFramework/UnityFramework.h' file not found

### ISSUE THREAD

**Issue by cliveleehere** [Unity-Technologies/uaal-example#2]
I followed the iOS example, and when I try to run the app, i get the above error in 
NativeiOSApp > NativeiOSApp > MainViewController.mm > line 4 
#include <UnityFramework/UnityFramework.h>

This is for xcode 11.2
Any help would be appreciated!

**Comment by cliveleehere** [comment]
Seems it happens for Simulators, but works for a real device. Closing

**Comment by cliveleehere** [comment]
I was able to build for Simulators by:
Player Settings -> Player -> iOS -> Other settings -> 
- unset 'Auto Graphics APIs'
- under 'Graphics APIs', add 'OpenGLES3' 
- For 'Target SDK', set it to 'Simulator SDK' (this should set the 'Architecture' to x86_64)
Then follow the rest of the steps!

**Comment by hrkd** [comment]
> Seems it happens for Simulators, but works for a real device. Closing

I had a same issue but it solved just switching `Player Settings > Target SDK` from `Simulator SDK` to `Device SDK`.

**Comment by chadobado** [comment]
Anyone know how to make this work with both SDKs to support simulator/preview and on-device?  I've tried exporting different x86/arm builds and bringing them into a shared workspace.. but with naming collisions between them, I'm not getting much further.
