### ISSUE TITLE
Hi can we disable Unity as a library feature from Unity Editor?

### ISSUE THREAD

**Issue by superbderrick** [Unity-Technologies/uaal-example#20]
Hi Unity forks,
Is there any setting options to disable "Unity As a library" feature in 2019.3 Editor.
Like versions prior to 2019.3 , I'like to use single configuration, Not separate configuration like Lib and Splash structure
 
Thanks 
Regard,
D

**Comment by emandravickas** [comment]
Hi!

No unfortunately this is a required project structure at the moment. Is there any particular reason you would like to go back to previous project structure?

Kind regards,
Edvinas

**Comment by superbderrick** [comment]
Hi !

Thanks kindly reply

Now on I have been making some unity plugins in order to use the functions(In-APP purchase or Oauth2 SDK) at once in multiple apps

My projects consisted of a single project structure but I solved with Unity 2019.3 

Thanks a lot , good care,

Derrick
