### ISSUE TITLE
AndroidX seems to break the player

### ISSUE THREAD

**Issue by a6h-s** [Unity-Technologies/uaal-example#22]
Hope this isn't a bad place to ask this. 

I tried to migrate the project to AndroidX using the instructions Flutter provides [here](https://flutter.dev/docs/development/androidx-migration)

The project then builds, but when I try to load Unity the whole app crashes. How do I handle this?

**Comment by Cliabhach** [comment]
Is there any stacktrace or error in the console?

**Comment by a6h-s** [comment]
I ended up figuring it out, it was a mistake on my side, no problems with the library. Should have closed this when I solved it myself, sorry!

**Comment by ROBYER1** [comment]
Is UAAL working fine with Flutter in the android studio/Xcode project?

**Comment by superbderrick** [comment]
https://github.com/juicycleff/flutter-unity-view-widget it might be helpful

**Comment by ROBYER1** [comment]
> https://github.com/juicycleff/flutter-unity-view-widget it might be helpful

Already spent a few working days trying to get that plugin working and it's about as reliable as the 113+ open issues would suggest. UAAL just works and has a good simple setup guide.
