### ISSUE TITLE
Remove the second icon

### ISSUE THREAD

**Issue by HappyOwca** [Unity-Technologies/uaal-example#35]
The read.me says
`After installation there will be two icons added on the device. To leave only the icon of the main activity, remove ... from the AndroidManifest.xml in unityLibrary`

What do the "..." mean exactly?

**Comment by KensonTsang** [comment]
comment line 8 <category android:name="android.intent.category.LAUNCHER" /> from unityLibrary/manifests/AndroidManifest/xml

<img width="1165" alt="Screenshot 2020-11-30 at 5 43 05 PM" src="https://user-images.githubusercontent.com/10267343/100593613-86a15200-3333-11eb-9030-303da93e8392.png">

**Comment by HappyOwca** [comment]
@KensonTsang 
I managed to find it on my own, but thanks anyway. Someone should update the readme.

**Comment by jari-immersal** [comment]
Readme still not updated, it has been 2 years. Also when I do what @KensonTsang says above only the unity part is launched when I start the app.
