### ISSUE TITLE
Android - wrong documentation

### ISSUE THREAD

**Issue by manake** [Unity-Technologies/uaal-example#89]
The documentation says "In Other Settings -> Configuration section -> select both Activity and GameActivity as Application Entry Point".

But such setting doesn't exist.

Link: https://github.com/Unity-Technologies/uaal-example/blob/master/docs/android.md

**Comment by berkbuzcu** [comment]
You need to update your Unity

**Comment by manake** [comment]
Thanks, it's solved.

GameActivity will be default since Unity 2023.2 for all new apps.
